### ISSUE TITLE
Feedback, shotgun's "right-click" sound implies you're suppose to "charge it up".

### ISSUE THREAD

**Issue by Layarion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#24]
The Right-Click of the shotgundoes more damage than left click, which is cool and fine. Nothing wrong with that, but it does the same amount of "extra" damage, even if you merely "tap" right-click.

However it makes a distinct "charging up" sound that clearly implies you were meant to "fully" charge it. Is merely "tapping" it for full power, the intended behavior?

As a side note, would be cool if the "right-click" shot a slug instead of a spread of pellets. It would be more useful on things that aren't point-blank range.

**Comment by infiniteblock** [comment]
Fixed in Dev.
