### ISSUE TITLE
Feedback, HUD's crosshair doesn't line up with the holosight.

### ISSUE THREAD

**Issue by Layarion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#26]
Use any of the three holosight attachments, and you'll see two crosshairs. The holosights, and the HUD's.

Problem is, their centers don't match, and it's very distracting.

I actually think it's the HUD's crosshair that's not centered. This is a 1600 by 900 screen, and the HUD's crosshairs center, isn't at 800, but instead it's left center arrow starts at 799, and ends at 804. 

**but instead of fixing the alignment**, how about when we ADS with a holosight attached, we just remove the HUD's crosshair? it would be much less distracting, and look much cleaner.

![image](https://user-images.githubusercontent.com/7917992/159619811-42453a55-a8fb-481b-a60b-25a3bc5d12cf.png)
![image](https://user-images.githubusercontent.com/7917992/159620065-a225a545-b048-434a-8765-3a380f54c68f.png)
![image](https://user-images.githubusercontent.com/7917992/159620083-93dd0625-f0a4-4b42-bcaf-65b29dcd239f.png)

**Comment by infiniteblock** [comment]
Fixed in Dev. when weapon is zoomed we just remove the HUD's crosshair...
