### ISSUE TITLE
Request: A fourth holosight, "dot" version.

### ISSUE THREAD

**Issue by Layarion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#27]
Instead of the top holosight, I'd like one on the bottom because I like less clutter.

![image](https://user-images.githubusercontent.com/7917992/159623496-ca10fd3e-b225-47db-b466-e3eb978796c6.png)
![image](https://user-images.githubusercontent.com/7917992/159623538-2c55ac6a-7d45-4867-b5cb-3590c9d43ff2.png)

If you think it wouldn't be too difficult for a noob to do, I could try making it myself. I'm not a noob to C#, so I already know some programming. I imagine most of the hard stuff has already been done, I think I would just have to copy pasta mostly. Still though, I haven't touched Java or MC mods under the hood before. What's your take on that?

**Comment by Layarion** [comment]
I'm trying to learn Java and how to import this existing uncompiled code into ItelliJ right now so that I can try and add this feature as a pull request right now. Don't know how to do any of the above so no idea how long it'll take, but this should be a fun little exercise for me.

**Comment by infiniteblock** [comment]
Done in Dev.
