### ISSUE TITLE
Idea, make Inertia Dampers consume power?

### ISSUE THREAD

**Issue by Layarion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#29]
Might be interesting to have higher amount of fall damage that gets absorbed by the perk, use a proportional amount of power?

I'm not dead set on it or anything, just thought it might be interesting to survive an insane fall but have no power left over because the fall would have killed you otherwise. So it just adds that "it's still got a potential of risk to it" element if you got caught with your pants down.

**Comment by Gliese-832-c** [comment]
Interesting idea. To expand on it, maybe make it use a quadratic or exponential formula? Falling 10 blocks barely consumes power, falling 50 blocks consumes some, falling 100 consumes a lot and falling 200 basically drains your battery. Of course you don't have to use those exact values, but you get the point.

**Comment by infiniteblock** [comment]
Not in 1.12.2
