### ISSUE TITLE
Enchantment rendering is bugged

### ISSUE THREAD

**Issue by 301Gabe** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#30]
**Describe the bug**
Whenever I'm using the mod, enchanted items have weird boxes around them. Not only that, but some tile entities are rendering weird in my inventory

**To Reproduce**
Unsure

**Expected behavior**
For the things to render normally

**Screenshots**
![2022-04-08_20 07 27](https://user-images.githubusercontent.com/66044944/162550636-d7a0f41a-e23a-42ba-9281-49af2fe46e4b.png)

**please complete the following information:**
 - Forge Version: 14.23.5.2859
 - Mods: Arcane Archives, Blood Magic, Extra Utilities, Guide-API, JEI, Matter Overdrive, MysticalLib
 - MO Version: 0.7.8

**Additional context**

**Comment by Layarion** [comment]
MC versoin 1.12.2 right?

and does this happen with vanilla enchanted swords or other things?

Does it only happen with things enchanted via table, forge, or both?

**Comment by Layarion** [comment]
![image](https://user-images.githubusercontent.com/7917992/162552724-dd4c5732-86cd-4439-82f2-28f4c4e566bd.png)
having trouble reproducing.

**Comment by Layarion** [comment]
Is this a "modpack" that I can download, or is this a custom set of mods you threw together for yourself?

**Comment by 301Gabe** [comment]
Just a couple of mods I threw together

**Comment by Layarion** [comment]
Could you do us a favor, and see if the issue still happens when you run the mod by itself? or find what mod this is for sure doing this.

**Comment by 301Gabe** [comment]
i can disable EU2, but for some reason I can't disable the mods that use guide-API

**Comment by Layarion** [comment]
Infinite thinks he found the issue, can you confirm: does this only happen when the item is in the first slot on the toolbelt?

**Comment by 301Gabe** [comment]
No? I'm pretty sure it's messed up no matter what hotbar it's on

**Comment by 301Gabe** [comment]
![Inked2022-04-08_20 07 27_LI](https://user-images.githubusercontent.com/66044944/162834483-ce2437ff-5505-4b8b-b55c-7f080ebadf5b.jpg)

**Comment by Layarion** [comment]
Sorry man, I have no idea what those are suppose to look like. Is the potion looking as it should?

**Comment by 301Gabe** [comment]
![2022-04-11_16 18 16](https://user-images.githubusercontent.com/66044944/162835225-126f880d-cc20-497e-9cb7-081c99f4fc78.png)
This is how it looks when MO is disabled

**Comment by 301Gabe** [comment]
![2022-04-11_16 22 47](https://user-images.githubusercontent.com/66044944/162835722-146407bc-63d0-4ef2-8461-bfc3f4281321.png)
And this is with it enabled

**Comment by Layarion** [comment]
Ok I only have JEI and MO CE installed via curseforge, and I am seeing this there as well.
![image](https://user-images.githubusercontent.com/7917992/162836747-bb562cb3-f909-41c3-9de0-8b2230bd30c5.png)

So it's not some sort of mod conflict.

**Comment by 301Gabe** [comment]
yeah, I made a separate modpack as well and I still have bugged textures. Here's the vanilla ones I've found
![2022-04-11_16 31 03](https://user-images.githubusercontent.com/66044944/162837112-e84de939-1e3e-487f-9965-16aa6d4da31f.png)

**Comment by infiniteblock** [comment]
Enchanted items are fixed in dev and the commit I did last night. will will have to check mob heads.

**Comment by 301Gabe** [comment]
ok. hope I didn't waste too much of your time

**Comment by infiniteblock** [comment]
It was a genuine bug just the source on GitHub had a commit missing so only was in released jars!, Have been holding back some render work that has code for the android part renders was tied up in that.
