### ISSUE TITLE
Rebalance failure rate of decomposer from 1.18 to 1.12 Lable:backport 

### ISSUE THREAD

**Issue by Layarion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#33]
https://discord.com/channels/703124643149643818/954638147944333322/965796655880372234

Version 1.12 might want to rebalance it's failure rate for more expensive items, like how the 1.18 version of the mod is doing it.

-From mod version 1.18 to 1.12

**Comment by infiniteblock** [comment]
That essentially makes it easier to replicate expensive items definitely won't backport.

**Comment by Layarion** [comment]
Whichever you decide, I think it should be consistent between the versions.
