### ISSUE TITLE
[BUG] Client render for enchanted tools in inv (also in JEI) and advancement section

### ISSUE THREAD

**Issue by fronczek7f** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#34]
MC: 1.12.2
Forge: 14.23.5.2847
Mod version: 0.7.8

Hello.
I had 2 bugs today after update mod from legacy to community edition and after enter to world i was see this:
![2022-04-21_20 55 20](https://user-images.githubusercontent.com/17440369/164534128-8cbd9d52-db88-43b9-a510-a7e3f9b6cad2.png)
![2022-04-21_20 57 56](https://user-images.githubusercontent.com/17440369/164534131-47246ba1-5d55-40bd-9d1f-216fa439db38.png)

**Comment by infiniteblock** [comment]
Picture 2 is fixed in dev,will double check it fixed advancement screen too, planing to release a new version in next day that has a massive amount of fixes and finishes alot of stuff that has never worked.

**Comment by fronczek7f** [comment]
ok, thanks for info :)
