### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by Maratons4** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#36]
I updated from the original mod to this version. When i opened the world, the missing registry entries appeared.

![unknown](https://user-images.githubusercontent.com/81237150/166138384-f400ea9b-7ce7-4b33-9fb5-8b95c5baa18c.png)

Further continuing to open the world, I got [this crash report.](https://pastebin.com/Gc2cZMaR)

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - Mods (Too big of a list, but can be seen in the crash report.)
 - MO Version: 0.7.9

**Comment by infiniteblock** [comment]
The missing blocks/items is fine we have changed the tiles and bounding box is no longer used, did the crash stop after reloading? I'm guessing it's because of old quests

**Comment by Maratons4** [comment]
I don't understand what do you mean by "reloading". If I open the world after it crashed once, it still crashes.

**Comment by infiniteblock** [comment]
could you send your playerdata file? its located in the save folder/playerdata/ ?

**Comment by Maratons4** [comment]
[c7303257.zip](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/8603854/c7303257.zip)

**Comment by infiniteblock** [comment]
[c7303257.zip](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/8608368/c7303257.zip)
try this let me know if it crashes i deleted the quest data.

**Comment by infiniteblock** [comment]
how did this go?

**Comment by Maratons4** [comment]
The world still crashes, exactly the same crash report.

**Comment by infiniteblock** [comment]
any chance i can get a copy of the world?

**Comment by Maratons4** [comment]
I'm sorry for the inactivity, I uploaded a copy of the world to [Mediafire](https://www.mediafire.com/file/jclu55ynh7722i0/1_12modded.zip/filel)
