### ISSUE TITLE
Add tuning parameter for World Gen structure rates

### ISSUE THREAD

**Issue by TheNumenorean** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#38]
I am seeing a lot of the cargo ships, and it would be nice if i could configure them to be rarer.

Two showed up within sight of spawn on a new world I just created:
![image](https://user-images.githubusercontent.com/809047/166840165-effa871d-9a79-4d4b-ad5c-03959e25ea98.png)

**Comment by TheNumenorean** [comment]
Make that 5
![Inked2022-05-04_18 17 17_LI](https://user-images.githubusercontent.com/809047/166840526-71c85b0a-e025-40c7-a8cd-43cbad406198.jpg)
afaf.png)

**Comment by infiniteblock** [comment]
they have been reset to default spawn ratio's as 1.7.10, but wont be adding a config option.
https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/commit/26918360b83a7480386bb104df458b8f8e9e3a1e

**Comment by TheNumenorean** [comment]
Thanks! I will add that to my project list.

**Comment by infiniteblock** [comment]
Added in Dev.
