### ISSUE TITLE
Holographic Sign text is centered too low

### ISSUE THREAD

**Issue by Deiwos** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#40]
**Describe the bug**
The text displayed on the Holographic Sign is centered on the lower half of the sign, so that multiline text extends off the bottom.

**To Reproduce**
1. Place a holographic sign
2. Enter text on sign

**Expected behavior**
Should be centered on the center.

**Screenshots**
https://i.imgur.com/KXSJrtv.png
https://i.imgur.com/2i7G9L3.png

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO Version: 0.7.9-universal

**Comment by infiniteblock** [comment]
Seems to only be in 0.7.9 looking to see what I changed somewhere that affected it.

**Comment by infiniteblock** [comment]
Fixed In Dev.
