### ISSUE TITLE
Sonic Shockwave is VERY large.

### ISSUE THREAD

**Issue by MagmaBro123** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#43]
**Describe the bug**
Title.

**To Reproduce**
Use the ability after becoming an Andriod and unlocking it.

**Expected behavior**
The Sonic Shockwave not being massive.

**Screenshots**
![2022-05-17_11 05 58](https://user-images.githubusercontent.com/51277766/168871072-236f5fe8-87a6-4678-a5ef-05046170aa50.png)

**please complete the following information:**
 - Forge Version: 2860.
 - Mods [e.g. mekanism, optifine] Just MatterOverdrive. No other mods installed.
 - MO Version [e.g. 0.7.4] 0.7.9.

**Additional context**
N/A

**Comment by infiniteblock** [comment]
Fixed in dev.

**Comment by MagmaBro123** [comment]
This also happened in the original mod, mainly why I switched to this version.
