### ISSUE TITLE
Cant break Stone Brick objects with omnitool

### ISSUE THREAD

**Issue by TheNumenorean** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#45]
**Describe the bug**
Using the omni-tool on stone brick blocks, like the basic block, stairs, slabs, etc., does not break the block.

**To Reproduce**
1. Place stone brick variants in the world
2. Hold right click with a charged omni tool while facing the block
3. The beam intersects the block, generates sparks, but the block does not get damaged or break.

**Expected behavior**
The block should break.

**Screenshots**
![image](https://user-images.githubusercontent.com/809047/172270195-014d6d72-6ce5-404c-a4b4-aab5b0be1b0d.png)

**please complete the following information:**
 - Forge Version: 2847
 - Mods [e.g. mekanism, optifine]: Many, can supply if needed
 - MO Version [e.g. 0.7.4]: commit #a509f9ddacd5830e2f481d4283b72bf2d21e17d5

**Comment by infiniteblock** [comment]
Do they have a harvest level? Had this issue with some mod blocks that don't set a harvest level and had to add one with craft tweaker

**Comment by TheNumenorean** [comment]
Poking around in the BlockStoneBrick class it doesnt look like it, so perhaps there need to be a default assumed? Presumably if a vanilla block can not have one it is not unreasonable for modded block to not have one either.

**Comment by infiniteblock** [comment]
Im not sure what we can do differently. as bypassing the check for if we can mine allows you to break the block but you don't have any drops.

We used this in our pack as a few mods don't set a harvest level.
import crafttweaker.item.IItemStack;
import crafttweaker.block.IBlock;
import crafttweaker.block.IBlockDefinition;

val Orebenitoite = <bigreactors:orebenitoite> as IBlock;
val Oreyellorite = <bigreactors:oreyellorite> as IBlock;
val Oreanglesite = <bigreactors:oreanglesite> as IBlock;
val Oreosmium = <mekanism:oreblock> as IBlock;

var OrebenitoiteDef = Orebenitoite.definition;
var OreyelloriteDef = Oreyellorite.definition;
var OreanglesiteDef = Oreanglesite.definition;
var OreosmiumDef = Oreosmium.definition;

OrebenitoiteDef.setHarvestLevel("pickaxe", 2);
OreyelloriteDef.setHarvestLevel("pickaxe", 3);
OreanglesiteDef.setHarvestLevel("pickaxe", 3);
OreosmiumDef.setHarvestLevel("pickaxe", 3);
