### ISSUE TITLE
Weapons Bugs 1 - Phaser Is Useless

### ISSUE THREAD

**Issue by Gliese-832-c** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#47]
**Describe the bug**
The Phaser is completely useless. It just doesn't do any damage. The setting (shift + RMB) doesn't matter. Upgrades/attachments don't do anything either. Just nothing.
(The only thing about it that might work is the stun effect, but that might also just be because the mobs I fired it at randomly happened to stop moving.)

**To Reproduce**
Just grab a Phaser and try firing it at a mob.

**Expected behavior**
The Phaser should be able to cause damage.

**Screenshots**
_Not applicable._

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO 0.8.1
 - Other mods:
![image](https://user-images.githubusercontent.com/55159077/179321084-02287774-1e43-4db1-8195-728108955763.png)
![image](https://user-images.githubusercontent.com/55159077/179321140-59a3157e-43fe-4e98-95f3-115169dc7f62.png)
![image](https://user-images.githubusercontent.com/55159077/179321157-55315aaf-f25f-4e3f-9bd5-efe14c7f4c6b.png)
![image](https://user-images.githubusercontent.com/55159077/179321173-0bed1fd7-9c3e-46dc-addd-94a9fe876dcf.png)
![image](https://user-images.githubusercontent.com/55159077/179321213-ed7986d1-b4b4-4fb7-bc26-b460d5785de7.png)
![image](https://user-images.githubusercontent.com/55159077/179321239-0c3e0329-87e3-428a-8902-c735a11162cb.png)

**Additional context**
_Not applicable._

**Comment by Gliese-832-c** [comment]
A weird GitHub bug prevented this issue from getting the usual bug label, it should probably be added manually.

**Comment by infiniteblock** [comment]
Fixed in Dev, was only issue in creative.
