### ISSUE TITLE
 Weapons Bugs 2 - Weapons Starting Out With Weird Bonuses

### ISSUE THREAD

**Issue by Gliese-832-c** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#48]
**Describe the bug**
The weapons start out with weird bonuses from out of nowhere. The phaser rifle has 112% damage, the plasma shotgun has 106%, ion sniper 105% and omni tool 114%.

**To Reproduce**
Either craft any weapon, or just grab it from JEI and look at the damage tooltip.

**Expected behavior**
The weapons should obviously start out at 100% (unless legendary of course!), then upgrades should modify the values.

**Screenshots**
![image](https://user-images.githubusercontent.com/55159077/179321942-9f942559-3ff1-4afc-be81-aef32fd79f34.png)
![image](https://user-images.githubusercontent.com/55159077/179321990-9c48ef85-07f1-4748-8ef5-45c193d99fc3.png)
I don't think I need to post all of them, you probably get it by now.

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO 0.8.1
 - Other mods:
![image](https://user-images.githubusercontent.com/55159077/179321084-02287774-1e43-4db1-8195-728108955763.png)
![image](https://user-images.githubusercontent.com/55159077/179321140-59a3157e-43fe-4e98-95f3-115169dc7f62.png)
![image](https://user-images.githubusercontent.com/55159077/179321157-55315aaf-f25f-4e3f-9bd5-efe14c7f4c6b.png)
![image](https://user-images.githubusercontent.com/55159077/179321173-0bed1fd7-9c3e-46dc-addd-94a9fe876dcf.png)
![image](https://user-images.githubusercontent.com/55159077/179321213-ed7986d1-b4b4-4fb7-bc26-b460d5785de7.png)
![image](https://user-images.githubusercontent.com/55159077/179321239-0c3e0329-87e3-428a-8902-c735a11162cb.png)

**Additional context**
_Not applicable._

**Comment by infiniteblock** [comment]
![image](https://user-images.githubusercontent.com/5800555/179336961-8cf34c09-3990-4ebc-a62d-424e0f62a9e0.png) Depending on the entity holding it the stats are increased. base levels for the weapons are just 9 ÷ 8 × 100 = 112.5 hence phaser rifle having a 12% increase

**Comment by infiniteblock** [comment]
Fixed in Dev.
