### ISSUE TITLE
Weapons Bugs 3 - VENOM Upgrade Can Go Into All Weapons

### ISSUE THREAD

**Issue by Gliese-832-c** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#49]
**Describe the bug**
I'm allowed to put the "Voxel Exaggerating Nullification Obliteration Matrix (VENOM)" upgrade into all of the weapons, but it only actually does something inside of the Omni Tool where it increases the mining speed.

**To Reproduce**
Just put the upgrade in question into a weapon of your choice in the Weapon Station.

**Expected behavior**
It should be blocked from going into other weapons. (Mostly to prevent people getting confused from putting it into other guns and expecting them to remove blocks, but also just general tidyness and making the mod feel more complete and better.) That is actually already a feature. For example, the Regenerative Converter upgrade cannot be installed in a Phaser Rifle. 

**Screenshots**

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO 0.8.1
 - Other mods:
![image](https://user-images.githubusercontent.com/55159077/179321084-02287774-1e43-4db1-8195-728108955763.png)
![image](https://user-images.githubusercontent.com/55159077/179321140-59a3157e-43fe-4e98-95f3-115169dc7f62.png)
![image](https://user-images.githubusercontent.com/55159077/179321157-55315aaf-f25f-4e3f-9bd5-efe14c7f4c6b.png)
![image](https://user-images.githubusercontent.com/55159077/179321173-0bed1fd7-9c3e-46dc-addd-94a9fe876dcf.png)
![image](https://user-images.githubusercontent.com/55159077/179321213-ed7986d1-b4b4-4fb7-bc26-b460d5785de7.png)
![image](https://user-images.githubusercontent.com/55159077/179321239-0c3e0329-87e3-428a-8902-c735a11162cb.png)

**Additional context**
_Not applicable._

**Comment by infiniteblock** [comment]
Fixed in dev.
