### ISSUE TITLE
Weapons Balancing Concerns

### ISSUE THREAD

**Issue by Gliese-832-c** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#51]
**Describe the bug**
The weapons are very unbalanced. The range is low on all of them but the sniper, the damage is very meager given the fact that they are futuristic high-end weapons. The accuracy is so low, it's irritating, especially with some of the upgrades. Also, why the hell does the scope change the damage or range? All it should do is make aiming easier...

**To Reproduce**
Just...boot up the game with the mod and try using the weapons.

**Expected behavior**
I understand that it might be difficult to come up with a good, balanced, system. Also, people will disagree about balancing all the time, so even if we find a good and consistent system, it will still not fit some people's needs. As such, I instead suggest the addition of more config options, where like the machine configs, where each value (energy usage, energy storage, matter storage, etc.) can be configured, every property of the weapons and the upgrades can be configured. I imagine it looking something like the following. (It doesn't have to follow that exact design, just a suggestion.)
```
weapons {
    phaser_rifle {
        # Phaser rifle damage
        D:phaser_rifle_damage=12.5

        # Phaser rifle range
        D:phaser_rifle_range=90.0

        # More stuff here
        ...
    }

    ion_sniper {
        # Ion sniper configs here
        ...
    }
   ...
}
```

**Screenshots**
_Not applicable._

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO 0.8.1
 - I don't think a modlist is needed given that this is not a bug per-se, but rather more of a suggestion.

**Additional context**
_Not applicable._

**Comment by infiniteblock** [comment]
Not in 1.12.2
