### ISSUE TITLE
Android Speed Upgrade FOV Is Messed Up

### ISSUE THREAD

**Issue by Gliese-832-c** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#52]
**Describe the bug**
When I get the speed upgrade as an android, my FOV goes down i.e. zooms in. However, when I hold any of the five MO weapons, the FOV goes back to normal. This only happens as an android with speed upgrades. Being a human or an android without speed upgrades does not do this. Each stage of the speed upgrade makes the problem progressively worse.
EDIT: It looks like when you run out of battery it actually does the opposite and turns the FOV very high up. I'm guessing these two are probably supposed to be inverted.

**To Reproduce**
Apply the speed upgrades as an android. Pay attention the FOV as you go through the four stages of it. Then try holding any weapon and compare it to holding nothing.

**Expected behavior**
At the very least, the speed upgrades should make your FOV zoom out. Though ideally, I'd prefer it if it wouldn't change your FOV at all (or only change it very slightly), as people play at their preferred FOVs and any permanent change to that by anything is annoying.

**Screenshots**
Not really applicable, it's kind of self-explanatory what FOV is and what a change in FOV means.

**please complete the following information:**
 - Forge Version: 14.23.5.2860
 - MO 0.8.1
 - Other mods:
![image](https://user-images.githubusercontent.com/55159077/179321084-02287774-1e43-4db1-8195-728108955763.png)
![image](https://user-images.githubusercontent.com/55159077/179321140-59a3157e-43fe-4e98-95f3-115169dc7f62.png)
![image](https://user-images.githubusercontent.com/55159077/179321157-55315aaf-f25f-4e3f-9bd5-efe14c7f4c6b.png)
![image](https://user-images.githubusercontent.com/55159077/179321173-0bed1fd7-9c3e-46dc-addd-94a9fe876dcf.png)
![image](https://user-images.githubusercontent.com/55159077/179321213-ed7986d1-b4b4-4fb7-bc26-b460d5785de7.png)
![image](https://user-images.githubusercontent.com/55159077/179321239-0c3e0329-87e3-428a-8902-c735a11162cb.png)

**Additional context**
_Not applicable._

**Comment by infiniteblock** [comment]
Fixed In Dev.
