### ISSUE TITLE
More configuration

### ISSUE THREAD

**Issue by BryceMalloy** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#53]
Hello, I would like to be able to configure the ability to unlock players from using either attack tree or defense tree as the mod pack I'm building makes other skills not work (definitely not MatterOverdrive's fault) and possibly have a black list of skills able to select in the upgrades menu, so I can remove the broken ones. I would like to give players more incentive to become an android.

**Comment by infiniteblock** [comment]
not in 1.12.2 sorry maybe in future versions
