### ISSUE TITLE
Android Skin always on!!!

### ISSUE THREAD

**Issue by KazutoKirigyua** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#54]
First of all! sorry for the bad writing, English is not my mother language.
So, When i turn into android, the android skin overlay my own skin, but i still got my hear (hat part of skin) and, the other ones that is in 3d part!
i do want to know if it has changed from the other versions like, Mo- Legacy edition!
but anyways, love this mod and i hope u guys can help me!!!

**Comment by infiniteblock** [comment]
Disabled for now.
