### ISSUE TITLE
[BUG] Rendering crash with Cyberware mod (1.12.2)

### ISSUE THREAD

**Issue by NovaLynxie** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#55]
**Describe the bug**
As soon as I try to add any cyberware arm or leg the game will instantly freeze and eventually crash due to the massive log spam in the console. The game will instantly freeze up and I cannot do anything except wait for it to crash or force close the game.
This effectively hard locks the player in singleplayer and causes players nearby affected cyber augmented player to crash in multiplayer until killed to remove their arms/legs.

**To Reproduce**
1. Go to cyberware robosurgeon and add cyber arm/leg to your player.
2. Enter the chamber and start the procedure to add said arm/leg.
3. Wait for the damage to finish once procedure is done, the game will instantly freeze at this point.
4. Console spam starts immediately in the background. See error in console.

**Expected behavior**
Expected procedure to complete normally and for me to be able to continue playing.

**Screenshots**
Unsure if this is related but the game render breaks horribly, does this and any player control becomes impossible.
![image](https://user-images.githubusercontent.com/21307676/181381263-761c2501-5187-4203-85e0-2ffaa170890f.png)

**please complete the following information:**
 - Forge Version: 14.23.5.2854
 - Mods: Cyberware 0.2.11
 - MO Version 0.8.1

**Additional context**
Crashes aren't easy to replicate since the game almost always just seizes up and stops working well before a crash.
I did manage to get it to crash out eventually. [Crash Report](https://gist.github.com/NovaLynxie/1f7912b887fa8defd5c56decf252fe3b)
Created issue report here for Cyberware -> [Issue Report](https://github.com/An-Sar/Cyberware/issues/172)

**Comment by NovaLynxie** [comment]
Did some testing and found something interesting. Changing the following setting in cyberware's config file 'cyberware.cfg' temporarily fixes the issue as a workaround for the crashing problem though not ideal as it means every single player would need to switch this setting else they would crash too.
```cfg
B:"Enable changes to player model (missing skin, missing limbs, Cybernetic limbs)"=false
```
It leads me to believe that Matter Overdrive Community edition is somehow messing with the player model while I am still a human player.
To confirm this, I swapped out community edition with the legacy edition of MO which I know works as intended and that does not cause the game to crash.

**Comment by DamondSword2247** [comment]
You might also want to look into compatibility with Armourer's Workshop cause with community MO it makes the player model and skins invisible when and when not an android. It works fine with legacy MO.

**Comment by NovaLynxie** [comment]
Hmm alright. I have tested cyberware against the legacy MO and that didn't have the issue, as stated before in previous comment.
Am still wondering what community MO is doing differently which is causing this crash.

**Comment by KazutoKirigyua** [comment]
Same! With community MO, cyberware render does crash the game! i would like to know why they change de render from the previous versions, just like the legacy one.
I won't change back to the Legacy MO, cuz it has not the same skills and for some reason (maybe just for me), messes up with my hitbox.
But definitely, i want to know, why to force the "Android" skin into the player

**Comment by infiniteblock** [comment]
Disabled for now. in 0.8,2
