### ISSUE TITLE
Add buildings generation white list dimensions

### ISSUE THREAD

**Issue by alecss131** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#56]
this can be tied to the generation of ores with a couple of lines of code, but I don’t want to forked and compile the mod from source. add another option in the settings is not so difficult

**Comment by infiniteblock** [comment]
are you interested in doing the code and i will add it?

**Comment by infiniteblock** [comment]
Will have a structure gen blacklist for dimension's in 0.8.5
