### ISSUE TITLE
Machines does not actually use energy!!!!!

### ISSUE THREAD

**Issue by KazutoKirigyua** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#57]
Well! i'm new to this version of MO, i used to play in 1.7.10, but then i ported to 1.12.2 and find out that this versions is better than the other ones;
The Bug is, the  machines like, matter replicator, decomposer, analyzer, are not using energy!

To Reproduce
I think u just need to load a map with the MO community edition
charge any machine (maybe with enderio conduits)
then u remove it! and maybe u'll see that the machine has a infinity source of energy

 - Forge Version: 14.23.5.2860
 - All Mods (https://drive.google.com/file/d/1KlXz_-ZoS7aUebZJ1Eu45XyuiTM0AOTD/view?usp=sharing)
 - MO Version [0.8.1]

Little vid to show!

https://user-images.githubusercontent.com/97145553/185199552-d34c924c-b9a9-48c1-8c71-16ace8393b38.mp4

**Comment by infiniteblock** [comment]
Fixed in 0.8.2!

**Comment by KazutoKirigyua** [comment]
I couldnt find this version!

**Comment by infiniteblock** [comment]
still working on it, will release it soon once i disable the android skin for now...

**Comment by KazutoKirigyua** [comment]
okay! i rly like what u doing! thx for all

**Comment by infiniteblock** [comment]
https://www.curseforge.com/minecraft/mc-mods/matter-overdrive-community-edition/files/4112184
