### ISSUE TITLE
Matter cannot be transfered out of Decomposers

### ISSUE THREAD

**Issue by Gamerboi12345** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#58]
![2022-08-28_15 18 07](https://user-images.githubusercontent.com/95109681/187096785-97a5219b-3c5f-41ac-8d72-3997573914b1.png)
![2022-08-28_15 18 14](https://user-images.githubusercontent.com/95109681/187096787-d0f2dca9-c702-4504-9ae5-d0a21d7531b4.png)
![2022-08-28_15 18 17](https://user-images.githubusercontent.com/95109681/187096789-406422a7-5bd7-40db-8968-f976d20b074e.png)

**Comment by infiniteblock** [comment]
Tested and working fine, most likely how u have the conduits setup....
