### ISSUE TITLE
[Suggestion] Mob Indicator Window Config Option

### ISSUE THREAD

**Issue by Rekag** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#59]
Hello

I would like to suggest adding the config option to disable the "mob indicators" window that starts to pop up once the player becomes an android.
I'd imagine that many players already have an indicator mod installed, and don't need a second one permanently baked in into a sci-fi mod.

Thank you
![2022-09-19_22 10 07](https://user-images.githubusercontent.com/67206172/191139383-3516dba8-7377-44fb-b3e8-abac2d86f0ce.png)

**Comment by infiniteblock** [comment]
Starting to work on this over next few days, will be released in 0.8.5

**Comment by infiniteblock** [comment]
Done
