### ISSUE TITLE
Disable crate and inscriber generation in village.

### ISSUE THREAD

**Issue by Ironnoob73** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#60]
![2022-11-28_19 47 44](https://user-images.githubusercontent.com/67966070/204270521-a8f86bd1-b13f-46ee-bd00-3b2e89168c70.png)
I don't want crate and inscriber generate in village, but the settings don't seem to be available in the config file.

**Comment by infiniteblock** [comment]
I have made a option in the config to disable it generating this in villages. In the 0.8.5 update not out yet.
