### ISSUE TITLE
CustomName String of Androids being flooded with the color code

### ISSUE THREAD

**Issue by Muffus16** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#61]
**Describe the bug**
Androids being found in Android Houses (i didn't check if it's the same for androids from other locations) will generate multiple of the same color code in den CustomName NBT Entry. In my Gameplay this lead until reaching the end of the string data type and results in a crash.

**To Reproduce**
install latest MO Version and check the NBT Tag CustomName for Androids spawned in Android Houses.

**Expected behavior**
Only one of the same kind of color/formatting codes should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/79163978/208253503-8b9ea80a-cbf5-43fc-a8bc-a078919dc354.png)

**please complete the following information:**
 - Forge Version: 14.23.5.2859
 - only MO for proof
 - MO Version 0.8.2

**Additional context**
Screenshot was taken from nbt studio with an seperate mc install only with MO.
In a Modpack i'm playing at the moment the bug lead to crashing the server because it caused the string to flood over the size of the data type.

**Comment by infiniteblock** [comment]
Fixed In Dev.
