### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by MRtecno98** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#62]
**Describe the bug**
Gradle compilation fails with unknown symbol error

**To Reproduce**
1. Clone the repo
2. Run `gradle build`

**Expected behavior**
Compilation completes succesfully

**Screenshots**
![image](https://user-images.githubusercontent.com/20360363/217039292-d2613369-7ac0-430e-81fe-11b9370a7853.png)

**please complete the following information:**
 - Forge Version: 14.23.5.2847 (from gradle.properties)
 - Mods: not applicable, i'm trying to compile the mod
 - MO Version: 0.8.1 (latest on the repo)

**Additional context**
Javac error:
```
import matteroverdrive.handler.HandleSkinClient;
                              ^
  symbol:   class HandleSkinClient
  location: package matteroverdrive.handler
```
Seems like a missing file, i could not find ANY mention of this file anywhere in the repo or the commit history, wtf?

**Comment by infiniteblock** [comment]
Fixed.
