### ISSUE TITLE
Console Spamming Weapon Stat Info

### ISSUE THREAD

**Issue by Rsslone** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#63]
**Describe the bug**
Console spams some information about weapon stats, even while empty.

**To Reproduce**
N/A

**Expected behavior**
For console to not spam this information.

**Screenshots**
https://i.imgur.com/fMI0sFs.png

**please complete the following information:**
 - Forge Version: forge-1.12.2-14.23.5.2860
 - Mods Alot
 - MO Version 1.12.2-0.8.2

**Comment by Rsslone** [comment]
I see it was changed here.
https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/commit/9283516693a5e62adddce03bf4b806801f7b0f2f
I'm going to try the version right before this and see if the issue persists.

**Comment by infiniteblock** [comment]
Fixed in Dev.
