### ISSUE TITLE
Plasma shotgun's left and right keys are reversed

### ISSUE THREAD

**Issue by goumo** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#68]
In 1.7.10 the right button is the "charge" to fire large bullets.

**Comment by infiniteblock** [comment]
just checked and its not.....

**Comment by goumo** [comment]
Have you not encountered this problem? Or is that how the weapon works?

**Comment by infiniteblock** [comment]
No I just fired up the latest build and left click is shoot right charges and fires....

**Comment by goumo** [comment]
I mean the left click is shooting multiple shots and the right click recharges to shoot one large shot, which is how it works in 1.7.10

**Comment by IPlayMinecraftYT** [comment]
are you sure you're using the community edition?

**Comment by goumo** [comment]
I'm pretty sure I'm using the community edition, and then the version is 0.8.3
