### ISSUE TITLE
Matter-pipe, heavy-matter pipe causes crash

### ISSUE THREAD

**Issue by unknownBugReporter** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#69]
Server crashed after i went up in nether (crashed because of heavy-matter pipe being unloaded?)

1. Go to the nether, end dimensions (seems it crashes with any other dimensions) while there's working matter pipe system
2. Get crashed

Excepted - nothing wouldn't happen

 - Forge Version: 14.23.5.2860
 - Mods : see in crash report
 - MO Version 0.8.3

[crash-2023-05-24_20.29.28-server.txt](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/11557609/crash-2023-05-24_20.29.28-server.txt)

**Comment by infiniteblock** [comment]
Fixed in Dev.

**Comment by Gdanycz** [comment]
> Fixed in Dev.

How to get this?
