### ISSUE TITLE
Enhance the gravity anomaly

### ISSUE THREAD

**Issue by dvdcorsair** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#70]
After restarting game/server a anomaly begin to eat everything around it, gravitational stabilizers they are not loaded in a chunk, but as soon as they are loaded, the anomaly stabilizes, I have already lost more than one stack of energy conductors
It is necessary to add time before the anomaly becomes destabilized

Steps to reproduce:
1. Build a fusion reactor and feed the anomaly with 1 million of mass and place around it gravitational stabilizers, place some fragile blocks as a energy conduits nearby the fusion reactor
2. Rejoin your world/restart server
3. It devoured the conductors of energy

Expected: gravitational anomaly won't destabilize after restarting server 

 - MO Version 0.8.3

**Comment by infiniteblock** [comment]
Fixed in dev.
