### ISSUE TITLE
[Suggestion] GalactiCraft integration

### ISSUE THREAD

**Issue by EngineerXL** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#71]
Integration with GalactiCraft idea:
1) Structures can spawn on planets and moons
2) Androids are immune to oxygen and pressure (ExtraPlanets) damage
3) Android player is immune to oxygen and pressure too

**Comment by infiniteblock** [comment]
side note warpdrive supports andorids and can override galactic craft air...

**Comment by EngineerXL** [comment]
I found, that ExtraPlanets has MatterOverdrive compatibility!
Android player does not take pressure damage in space, because mod gives player [valid spacesuit](https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/handlers/MainHandlerServer.java#L402).
Also, GalactiCraft without addons seems to [have support](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/fc796c0ec3e5f6ded60921afa1f153a36034a5ec/src/main/java/micdoodle8/mods/galacticraft/core/util/CompatibilityManager.java#L63) and work with android player

**Comment by infiniteblock** [comment]
0.8.5 will generate structures in all worlds except the ones that are black listed. sand pit house will only spawn in deserts... underwater will still only gen in oceans
