### ISSUE TITLE
how to get molten tritanium in survival?

### ISSUE THREAD

**Issue by cross5123** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#78]
I found a molten tritanium in a bucket in the creative, and realized that it would be perfect for my traps intended for friends. But I still did not understand how and where to get it, maybe it is generated somewhere in the world or can it be created in any way? Version 1.12.2
I'm sorry if I'm writing in the wrong place

**Comment by Gandalf360one** [comment]
Will be used in Tconstruct for example
