### ISSUE TITLE
multiple questions

### ISSUE THREAD

**Issue by kodamant** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#79]
how do i store matter plasma or use matter plasma containers, how do i boost my fusion reactors power, and how in the kentucky fried fuck does the dimensional reactor work?

**Comment by kodamant** [comment]
i should add ive gotten the dimensional reactor to spark and make noise but its still not generating power

**Comment by infiniteblock** [comment]
dimensional reactor isn't working, boost fusion reactor by giving it more mass.
