### ISSUE TITLE
[Bug]:  No recipe for ingots from tritanium block

### ISSUE THREAD

**Issue by zhongjiedong** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#85]
### Forge Version

14.23.5.2860

### Matter Overdrive Community Edition Version

0.8.5

### Reproduction steps

Try and put the tritanium block in any crafting interface, JEI also does not list any recipe

**Comment by perevozke** [comment]
something on ur side
![image](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/assets/68667665/94c8632b-4ccb-46fb-8232-1eee7198efee)
MC 1.12.2, MO 0.8.5

**Comment by perevozke** [comment]
probably kubejs/crafttweaker(scripts) folders
but i think if darkosto(SF4 dev) wanted to ingots not craft from block - there is a reason

**Comment by zhongjiedong** [comment]
Mm that's the issue, the recipe existed before I updated

**Comment by perevozke** [comment]
send link where u took files for update(and for what version u updated)

**Comment by zhongjiedong** [comment]
https://www.curseforge.com/minecraft/mc-mods/matter-overdrive-community-edition/files/5114422

community edition I downloaded

Legacy edition https://www.curseforge.com/minecraft/mc-mods/matteroverdrive-legacy/files/all?page=1&pageSize=20&showAlphaFiles=show

Not sure which one though it says 7.0.0 in the sf4 modpack

**Comment by perevozke** [comment]
okay, i think i fixed this think for u
replace file at this location: corefolder/scripts/crafttweaker/recipes/mods/matterOverdrive.zs
[matterOverdrive.zip](https://github.com/user-attachments/files/15931071/matterOverdrive.zip)
U NEED TO EXTRACT FILE, BECAUSE I CANT SEND .ZS

**Comment by perevozke** [comment]
this is client version, if u using server u also need server side script so let me know if this needed and if my script will fix ur problem

**Comment by zhongjiedong** [comment]
I need a server script please, thank you very much for your time :)

**Comment by perevozke** [comment]
are u using server pack from cf? 
https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3565683
or u take it somewhere else? if from cf page or cf app, replace file at the same folder path
[matterOverdrive.zip](https://github.com/user-attachments/files/15931299/matterOverdrive.zip)
i downloaded server pack, because it's faster than check diffs in files so u can dont worry about something broke

**Comment by zhongjiedong** [comment]
yep server pack for sf4, thank you I will give this a try

**Comment by zhongjiedong** [comment]
does it need to be on both server and client side? I did put the script into the server but still no recipe for block to ingot

**Comment by perevozke** [comment]
okay just cancel all changes
put this file info client script and server script folders
[matterblock.zip](https://github.com/user-attachments/files/15937592/matterblock.zip)
